plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.shifaurrehman.mynativeapp.backgroundlogger'
version = '0.7.10'

android {
  namespace "com.shifaurrehman.mynativeapp.backgroundlogger"
  defaultConfig {
    versionCode 1
    versionName "0.7.10"
  }
  lintOptions {
    abortOnError false
  }
}
